# Generated by Django 5.1.6 on 2025-02-24 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedombooks_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='freedombooks_core.tagsmodel'),
        ),

    ]
