# Generated by Django 5.1.6 on 2025-02-25 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedombooks_core', '0002_alter_bookmodel_tags_remove_bookmodel_text_hook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='text_hook',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freedombooks_core.textmodel'),
        ),
    ]
