# Generated by Django 5.1.6 on 2025-03-07 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freedombooks_core', '0003_remove_bookmodel_text_file_hook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textmodel',
            name='text_file_hook',
        ),
    ]
