# Generated by Django 5.1.6 on 2025-02-25 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedombooks_core', '0003_remove_bookmodel_text_hook_bookmodel_text_hook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='text_hook',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='freedombooks_core.textmodel'),
        ),
    ]
