# Generated by Django 5.1.6 on 2025-02-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedombooks_core', '0004_alter_bookmodel_text_hook'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='author',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
