# Generated by Django 5.1.6 on 2025-03-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedombooks_core', '0004_remove_textmodel_text_file_hook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='text_hook',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='TextModel',
        ),
    ]
