# Generated by Django 5.1.6 on 2025-02-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedombooks_core', '0005_bookmodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='author',
            field=models.CharField(blank=True, default='Unknown author', max_length=128, null=True),
        ),
    ]
