# Generated by Django 5.1.6 on 2025-03-07 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freedombooks_core', '0005_alter_bookmodel_text_hook_delete_textmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFiles',
        ),
    ]
